config/routes.rb
Rails.application.routes.draw do
  resources :clubs
    scope module: :api, defaults: {format: :json} do
    %w(v1).each do |version|
      namespace version.to_sym do
        resource :configuration, only: %w(show)
        resource :user_token, path: :token, only: %w(create destroy update)
        resources :users, only: %w(create update show) do
          resources :questions, only: %w(index)
          collection do
            post :forgot_password
            put :reset_password
          end
        end
      end
    end
  end

  devise_for :users, class_name: 'FormUser', :controllers => {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations:      'users/registrations'
  }
  root 'clubs#index'

end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/controllers/clubs_controller.rb
 
 
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json, :js

  def index
    @clubs = Club.all
  end 

  def show
  end 

  def new 
    @club = Club.new
  end 

  def edit
  end 

  def create
    @club = Club.new(club_params)
    @club.save
    respond_with(@club)
  end 

  def update
    @club.update(club_params)
    flash[:notice] = 'Club was successfully updated.'
    respond_with(@club)
  end 

  def destroy
    @club.destroy
    redirect_to clubs_url, notice: 'Club was successfully destroyed.'
  end 

  private
    def set_club
      @club = Club.find(params[:id])
    end 

    def club_params
      params.require(:club).permit(:name, :number, :location, :email, :site, :telephone) 
    end 
end
 

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.haml
= simple_form_for(@club, layout: :horizontal) do |f|
  .form-inputs
    = f.input :name,      class: 'form-control'
    = f.input :number,    class: 'form-control'
    = f.input :location,  class: 'form-control'
    = f.input :email,     class: 'form-control'
    = f.input :site,      class: 'form-control'
    = f.input :telephone, class: 'form-control'

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/clubs/edit.html.haml
.page-header
  = link_to clubs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @club, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing club

= render 'form'

app/views/clubs/index.html.haml
.page-header
  = link_to new_club_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Club
  %h1 Listing clubs

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Number
        %th Location
        %th Email
        %th Site
        %th Telephone
        %th
        %th
        %th

    %tbody
      - @clubs.each do |club|
        %tr
          %td= club.name
          %td= club.number
          %td= club.location
          %td= club.email
          %td= club.site
          %td= club.telephone
          %td= link_to 'Show', club
          %td= link_to 'Edit', edit_club_path(club)
          %td= link_to 'Destroy', club, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/clubs/new.html.haml
.page-header
  = link_to clubs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New club

= render 'form'

app/views/clubs/show.html.haml
.page-header
  = link_to clubs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_club_path(@club), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show club

%dl.dl-horizontal
  %dt Name:
  %dd= @club.name
  %dt Number:
  %dd= @club.number
  %dt Location:
  %dd= @club.location
  %dt Email:
  %dd= @club.email
  %dt Site:
  %dd= @club.site
  %dt Telephone:
  %dd= @club.telephone